// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	dtos "github.com/edgexfoundry/app-record-replay/pkg/dtos"
	mock "github.com/stretchr/testify/mock"
)

// RecordManager is an autogenerated mock type for the RecordManager type
type RecordManager struct {
	mock.Mock
}

// CancelRecording provides a mock function with given fields:
func (_m *RecordManager) CancelRecording() {
	_m.Called()
}

// CancelReplay provides a mock function with given fields:
func (_m *RecordManager) CancelReplay() {
	_m.Called()
}

// ExportRecordedData provides a mock function with given fields:
func (_m *RecordManager) ExportRecordedData() (dtos.RecordedData, error) {
	ret := _m.Called()

	var r0 dtos.RecordedData
	var r1 error
	if rf, ok := ret.Get(0).(func() (dtos.RecordedData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() dtos.RecordedData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dtos.RecordedData)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportRecordedData provides a mock function with given fields: _a0
func (_m *RecordManager) ImportRecordedData(_a0 dtos.RecordedData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.RecordedData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordingStatus provides a mock function with given fields:
func (_m *RecordManager) RecordingStatus() dtos.RecordStatus {
	ret := _m.Called()

	var r0 dtos.RecordStatus
	if rf, ok := ret.Get(0).(func() dtos.RecordStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dtos.RecordStatus)
	}

	return r0
}

// ReplayStatus provides a mock function with given fields:
func (_m *RecordManager) ReplayStatus() dtos.ReplayStatus {
	ret := _m.Called()

	var r0 dtos.ReplayStatus
	if rf, ok := ret.Get(0).(func() dtos.ReplayStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dtos.ReplayStatus)
	}

	return r0
}

// StartRecording provides a mock function with given fields: request
func (_m *RecordManager) StartRecording(request dtos.RecordRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.RecordRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartReplay provides a mock function with given fields: request
func (_m *RecordManager) StartReplay(request dtos.ReplayRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.ReplayRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRecordManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewRecordManager creates a new instance of RecordManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecordManager(t mockConstructorTestingTNewRecordManager) *RecordManager {
	mock := &RecordManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
