// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpController is an autogenerated mock type for the HttpController type
type HttpController struct {
	mock.Mock
}

// AddRoutes provides a mock function with given fields:
func (_m *HttpController) AddRoutes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewHttpController interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpController creates a new instance of HttpController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpController(t mockConstructorTestingTNewHttpController) *HttpController {
	mock := &HttpController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
